new Vue({
    el: '#app',
    data: {
        textboxValue: '',
        radioValue: '',
        checkboxChecked: false,
        selectedOption: '',
        searchQuery: '',
        currentPage: 1,
        itemsPerPage: 5,
        pagesRange: 3,
        tableData: [
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            { name: 'Item 1', value: 'Value 1' },
            { name: 'Item 2', value: 'Value 2' },
            { name: 'Item 3', value: 'Value 3' },
            { name: 'Item 4', value: 'Value 4' },
            { name: 'Item 5', value: 'Value 5' },
            { name: 'Item 6', value: 'Value 6' },
            { name: 'Item 7', value: 'Value 7' },
            { name: 'Item 8', value: 'Value 8' },
            { name: 'Item 9', value: 'Value 9' },
            { name: 'Item 10', value: 'Value 10' },
            { name: 'Item 11', value: 'Value 11' },
            { name: 'Item 12', value: 'Value 12' },
            { name: 'Item 13', value: 'Value 13' },
            { name: 'Item 14', value: 'Value 14' },
            { name: 'Item 15', value: 'Value 15' },
            
        ]
    },
    computed: {
        filteredData() {
            const searchQuery = this.searchQuery.toLowerCase();
            return this.paginatedData().filter(item =>
                item.name.toLowerCase().includes(searchQuery) ||
                item.value.toLowerCase().includes(searchQuery)
            );
        },
        totalPages() {
            return Math.ceil(this.tableData.length / this.itemsPerPage);
        },
        paginatedPages() {
            const pages = [];
            const totalPages = this.totalPages;
            const start = Math.max(1, this.currentPage - this.pagesRange);
            const end = Math.min(totalPages, this.currentPage + this.pagesRange);

            for (let i = start; i <= end; i++) {
                pages.push(i);
            }
            return pages;
        }
    },
    methods: {
        handleSubmit() {
            alert('Form submitted!');
            this.resetForm();
        },
        resetForm() {
            this.textboxValue = '';
            this.radioValue = '';
            this.checkboxChecked = false;
            this.selectedOption = '';
        },
        paginatedData() {
            const start = (this.currentPage - 1) * this.itemsPerPage;
            const end = start + this.itemsPerPage;
            return this.tableData.slice(start, end);
        },
        changePage(page) {
            if (page < 1 || page > this.totalPages) return;
            this.currentPage = page;
        }
    }
});
